import type { Competencia } from "@/types";

export const COMPETENCIAS: Competencia[] = [
  {
    id: "comp1",
    nombre: "Trabajo en Equipo",
    descripcion: "Capacidad para colaborar efectivamente con otros miembros del equipo hacia objetivos comunes.",
    tipo: "Organizacional",
    nivel: "Nivel requerido: 4/5",
    nivelActual: 4,
    nivelEsperado: 5,
    evaluados: 12,
  },
  {
    id: "comp2",
    nombre: "Innovación y Creatividad",
    descripcion: "Habilidad para generar ideas novedosas y encontrar nuevas formas de abordar los retos.",
    tipo: "Por nivel",
    nivel: "Nivel actual: 2/5",
    nivelActual: 2,
    nivelEsperado: 5,
    evaluados: 8,
  },
  {
    id: "comp3",
    nombre: "Adaptabilidad al Cambio",
    descripcion: "Flexibilidad para ajustarse a nuevas circunstancias y procesos de trabajo.",
    tipo: "Organizacional",
    nivel: "Nivel requerido: 3/5",
    nivelActual: 3,
    nivelEsperado: 5,
    evaluados: 54,
  },
  {
    id: "comp4",
    nombre: "Comunicación Efectiva",
    descripcion: "Habilidad para transmitir información de manera clara, concisa y apropiada al contexto.",
    tipo: "Organizacional",
    nivel: "Nivel requerido: 4/5",
    nivelActual: 4,
    nivelEsperado: 5,
    evaluados: 30,
  },
  {
    id: "comp5",
    nombre: "Toma de Decisiones",
    descripcion: "Capacidad para analizar situaciones complejas y tomar decisiones informadas bajo presión.",
    tipo: "Por nivel",
    nivel: "Nivel actual: 4/5",
    nivelActual: 4,
    nivelEsperado: 5,
    evaluados: 19,
  },
  {
    id: "comp6",
    nombre: "Pensamiento Analítico",
    descripcion: "Habilidad para descomponer problemas complejos, identificar patrones y encontrar soluciones basadas en datos.",
    tipo: "De la tarea",
    nivel: "Nivel actual: 3/5",
    nivelActual: 3,
    nivelEsperado: 5,
    evaluados: 47,
  },
];
