import type { User } from "@/types";

export const USERS: User[] = [
  {
    id: "u-sara",
    name: "Sara Jennifer Olarte Peña",
    email: "sara.olarte@inmov.com",
    role: "colaborador",
    cargo: "Auxiliar Administrativo",
    cargoId: "cargo-aux-admin",
    departamento: "Contabilidad",
    area: "Contabilidad",
    sede: "Bogotá",
    nivel: "operativo",
    bandaSalarial: "B1",
    liderDirectoId: "u-rodrigo",
    diasEnEmpresa: 365,
  },
  {
    id: "u-deisy",
    name: "Deisy Natalia Gómez Valdés",
    email: "deisy.gomez@inmov.com",
    role: "colaborador",
    cargo: "Agente Call Center y Digitador",
    cargoId: "cargo-call-center",
    departamento: "Operaciones",
    area: "Operaciones",
    sede: "Bogotá",
    nivel: "operativo",
    bandaSalarial: "B1",
    liderDirectoId: "u-rodrigo",
    diasEnEmpresa: 280,
  },
  {
    id: "u-rodrigo",
    name: "Rodrigo Garzón Latorre",
    email: "rodrigo.garzon@inmov.com",
    role: "lider",
    cargo: "Coordinador de Operaciones",
    cargoId: "cargo-coord-ops",
    departamento: "Operaciones",
    area: "Operaciones",
    sede: "Bogotá",
    nivel: "tactico",
    bandaSalarial: "B2",
    liderDirectoId: "u-sindy",
    diasEnEmpresa: 720,
  },
  {
    id: "u-carlos",
    name: "Carlos Martínez",
    email: "carlos.martinez@inmov.com",
    role: "lider",
    cargo: "Tech Lead",
    cargoId: "cargo-tech-lead",
    departamento: "Tecnología",
    area: "Tecnología",
    sede: "Bogotá",
    nivel: "tactico",
    bandaSalarial: "B2",
    liderDirectoId: "u-sindy",
    diasEnEmpresa: 920,
  },
  {
    id: "u-kevin",
    name: "Kevin Núñez",
    email: "kevin.nunez@inmov.com",
    role: "colaborador",
    cargo: "Desarrollador Frontend",
    cargoId: "cargo-dev-frontend",
    departamento: "Tecnología",
    area: "Tecnología",
    sede: "Medellín",
    nivel: "operativo",
    bandaSalarial: "B1",
    liderDirectoId: "u-carlos",
    diasEnEmpresa: 697,
  },
  {
    id: "u-emily",
    name: "Emily Luna",
    email: "emily.luna@inmov.com",
    role: "colaborador",
    cargo: "Diseñadora UX/UI",
    cargoId: "cargo-ux-designer",
    departamento: "Tecnología",
    area: "Tecnología",
    sede: "Cali",
    nivel: "operativo",
    bandaSalarial: "B1",
    liderDirectoId: "u-carlos",
    diasEnEmpresa: 412,
  },
  {
    id: "u-laura",
    name: "Laura Herrera",
    email: "laura.herrera@inmov.com",
    role: "lider",
    cargo: "Coordinadora Comercial",
    cargoId: "cargo-coord-comercial",
    departamento: "Comercial",
    area: "Comercial",
    sede: "Bogotá",
    nivel: "tactico",
    bandaSalarial: "B2",
    liderDirectoId: "u-sindy",
    diasEnEmpresa: 543,
  },
  {
    id: "u-sindy",
    name: "Sindy Caicedo",
    email: "sindy.caicedo@inmov.com",
    role: "admin",
    cargo: "HR Manager",
    cargoId: "cargo-hr-manager",
    departamento: "Talento Humano",
    area: "Talento Humano",
    sede: "Bogotá",
    nivel: "estrategico",
    bandaSalarial: "B3",
    liderDirectoId: null,
    diasEnEmpresa: 1100,
  },
];

export function getUserById(id: string): User | undefined {
  return USERS.find((u) => u.id === id);
}

export function getColaboradoresDeLider(liderId: string): User[] {
  return USERS.filter((u) => u.liderDirectoId === liderId);
}
